FROM nginx:latest

COPY ./dist /usr/share/nginx/html
COPY ./src/assets /usr/share/nginx/html/src/assets
COPY ./public/icons/tourlist.ico /usr/share/nginx/html/src/favicon.ico

COPY ./nginx/deploy/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/deploy/default.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]