FROM openjdk:17
ARG JAR_FILE=tourlist_checklist*.jar
WORKDIR /app
COPY /build/libs/${JAR_FILE} ./checklist.jar
ENV TZ=Asia/Seoul
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=default", "./checklist.jar"]
