FROM openjdk:17
ARG JAR_FILE=tourlist_gateway*.jar
WORKDIR /app
COPY /build/libs/${JAR_FILE} ./tour.jar
ENV TZ=Asia/Seoul
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=default", "./tour.jar"]
