FROM openjdk:17
ARG JAR_FILE=tourlist_place*.jar
WORKDIR /app
COPY /build/libs/${JAR_FILE} ./place.jar
ENV TZ=Asia/Seoul
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=default", "./place.jar"]
